"""Create PangoT tables

Revision ID: 273e298aa774
Revises: 
Create Date: 2025-12-15 11:09:37.444583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273e298aa774'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calculated_fixes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=80), nullable=True),
    sa.Column('pango_id', sa.String(length=10), nullable=True),
    sa.Column('calc_lat', sa.Float(), nullable=True),
    sa.Column('calc_lon', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calculated_fixes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calculated_fixes_group_id'), ['group_id'], unique=False)

    op.create_table('raw_bearings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=80), nullable=True),
    sa.Column('pango_id', sa.String(length=10), nullable=True),
    sa.Column('observer', sa.String(length=10), nullable=True),
    sa.Column('obs_lat', sa.Float(), nullable=True),
    sa.Column('obs_lon', sa.Float(), nullable=True),
    sa.Column('bearing', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('gps_accuracy', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_bearings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_bearings_group_id'), ['group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_bearings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_bearings_group_id'))

    op.drop_table('raw_bearings')
    with op.batch_alter_table('calculated_fixes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calculated_fixes_group_id'))

    op.drop_table('calculated_fixes')
    op.drop_table('animals')
    # ### end Alembic commands ###
